---
dataset_name: CIFAR10
model_name: densenet40
distributed_algorithm: fed_avg_qat
optimizer_name: SGD
worker_number: 10
batch_size: 64
round: 100
learning_rate_scheduler_name: CosineAnnealingLR
epoch: 5
learning_rate: 0.1
...
