---
use_slow_performance_metrics: true
use_amp: false
model_name: TwoGCN
round: 100
worker_number: 100
epoch: 1
learning_rate: 0.001
fake_weight_decay: 0.01
distributed_algorithm: fed_gnn
dataset_kwargs:
  dataset_type: graph
dataloader_kwargs:
  batch_number: 10
  num_neighbor: 10
algorithm_kwargs:
  share_feature: false
  edge_drop_rate: 0.99
