---
use_slow_performance_metrics: true
use_amp: false
model_name: TwoGCN
distributed_algorithm: fed_sage_plus
epoch: 1
learning_rate: 0.001
fake_weight_decay: 0.01
round: 100
worker_number: 100
algorithm_kwargs:
  share_feature: true
  edge_drop_rate: 0.99
dataloader_kwargs:
  server_batch_size: 1000
  batch_number: 10
  num_neighbor: 10
