---
dataset_name: CIFAR100
model_name: densenet40
distributed_algorithm: sign_SGD
optimizer_name: SGD
worker_number: 10
round: 1
learning_rate_scheduler_name: CosineAnnealingLR
epoch: 100
learning_rate: 0.1
algorithm_kwargs:
  distribute_init_parameters: false
