---
dataset_name: MNIST
model_name: LeNet5
distributed_algorithm: GTG_shapley_value
optimizer_name: SGD
worker_number: 2
round: 20
learning_rate_scheduler: CosineAnnealingLR
epoch: 1
learning_rate: 0.01
parallel_number: 1
log_level: INFO
...
