---
use_slow_performance_metrics: true
use_amp: false
model_name: TwoGCN
distributed_algorithm: fed_cluster_gcn
epoch: 1
learning_rate: 0.001
fake_weight_decay: 0.01
round: 100
worker_number: 100
algorithm_kwargs:
  share_feature: true
  edge_drop_rate: 0.99
  warmup_rounds: 1
  node_sample_percent: 0.7
dataloader_kwargs:
  batch_number: 10
  num_neighbor: 10
