---
dataset_name: MNIST
model_name: lenet5
distributed_algorithm: QSGD
worker_number: 2
round: 1
learning_rate_scheduler_name: CosineAnnealingLR
epoch: 10
batch_size: 64
learning_rate: 0.001
algorithm_kwargs:
  distribute_init_parameters: false
