---
dataset_name: TWeibo
model_name: TwoGCN
distributed_algorithm: fed_aas
epoch: 1
learning_rate: 0.001
fake_weight_decay: 0
round: 50
worker_number: 50
use_amp: false
algorithm_kwargs:
  share_feature: true
  edge_drop_rate: 0.99
dataloader_kwargs:
  batch_number: 10
  num_neighbor: 10
