---
dataset_name: imdb
model_name: TransformerClassificationModel
distributed_algorithm: fed_dropout_avg
optimizer_name: SGD
worker_number: 10
batch_size: 64
round: 100
learning_rate_scheduler_name: CosineAnnealingLR
epoch: 5
learning_rate: 0.01
algorithm_kwargs:
  dropout_rate: 0.3
  random_client_number: 5
dataset_kwargs:
  input_max_len: 300
  dataset_type: text
  tokenizer:
    type: spacy
model_kwargs:
  word_vector_name: glove.6B.100d
  num_encoder_layer: 2
  d_model: 100
  nhead: 5
